### PR TITLE
Allow toggling of the view counter and upload date

### PR DESCRIPTION
**Pull request by dhanasekaranc**
This PR address https://github.com/ynshung/better-yt-shorts/issues/161
Description
This pull request allow toggling of the view counter and upload date so that it can be displayed or not in the view.

Changes Made
Updated the Info file to display view counter and upload date. Added translation for all the locale files too.

### CODE REVIEW

**Comment by tiagohconte** [comment]
LGTM! But for this PR it's better to just add the English message and wait for other people to translate to their languages.

**Comment by dhanasekaranc** [comment]
@tiagohconte @ynshung should I remove those translations and update the PR then?

**Comment by ynshung** [comment]
> @tiagohconte @ynshung should I remove those translations and update the PR then?

Yup you can just remove them so the others can help to translate it

**Review by adsuth — APPROVED** [review]
LGTM as well, thanks!

**Review by ynshung — COMMENTED** [review]
LGTM, nice job @dhanasekaranc! Thank you for the contribution

**Comment by dhanasekaranc** [comment]
Thanks @ynshung for removing the translations

**Pull request merged**
