### PR TITLE
add: hebrew localization

### PR DESCRIPTION
**Pull request by erelado**
Added Hebrew translations for the different messages

### CODE REVIEW

**Comment by ynshung** [comment]
Wow, didn't expect someone to make a translation so quick. Thank you so much!

I'm also planning to add multilingual support for the webstore as well. So once everything in v3 is finalized (or earlier) I will let you know so you can help translate it too.

**Comment by ynshung** [comment]
Hi @erelado! Could you help to translate some of the [newly added messages](https://github.com/ynshung/better-yt-shorts/commits/v3/_locales/en/messages.json) for your language? Additionally, if you're inclined, you can help us in localizing the store listing [here](https://github.com/ynshung/better-yt-shorts/tree/v3/store-desc) which would greatly contribute to expanding the extension's reach worldwide. Thank you!

**Comment by erelado** [comment]
Hello, @ynshung. As the PO, please add all the missing strings in English to the other languages' json files, so that people will be aware of what needs to be translated, then I would love to help translate those.

**Comment by erelado** [comment]
Nothing yet? that's unfortunate.

**Comment by erelado** [comment]
Nothing yet @ynshung? that's unfortunate.

**Comment by ynshung** [comment]
Hi @erelado, sorry for the late reply since I was planning and setting up translations at that time. You can refer to the new [Translation](https://github.com/ynshung/better-yt-shorts#translation) section at the readme file. In short, you can join the POEditor project under the Hebrew language, then complete the remaining untranslated strings at the bottom of the page. Thank you!

**Pull request merged**
