### PR TITLE
fix autoplay for different languages

### PR DESCRIPTION
**Pull request by monsieurvor**
aria label "next video" is based on language, so can't be used in query selector

### CODE REVIEW

**Comment by DarkeleEXE** [comment]
just FYI, if I try your new selector I get the following:
image

The button that gets selected here is the "Previous video" button (german:"Vorheriges Video").

**Comment by monsieurvor** [comment]
Oh, it worked on my end, haha.
I changed it to this:
`document.querySelector('#navigation-button-down > .style-scope.ytd-shorts > yt-button-shape > button.yt-spec-button-shape-next.yt-spec-button-shape-next--text.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-xl.yt-spec-button-shape-next--icon-button');`

Does this grab the right button?

**Comment by DarkeleEXE** [comment]
> Oh, it worked on my end, haha. I changed it to this: `document.querySelector('#navigation-button-down > .style-scope.ytd-shorts > yt-button-shape > button.yt-spec-button-shape-next.yt-spec-button-shape-next--text.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-xl.yt-spec-button-shape-next--icon-button');`
> 
> Does this grab the right button?

This works for me in german! :)

**Comment by ynshung** [comment]
Thank you for the help @monsieurvor!

**Comment by monsieurvor** [comment]
@sus2790 This should be fixed in version 2.1.5

**Pull request merged**
