### PR TITLE
Partial code refactor for lint compatibility

### PR DESCRIPTION
**Pull request by tiagohconte**
PR to implement changes that maintain the current functionality while preparing for easier integration with lint tools in the future.

### CODE REVIEW

**Comment by ynshung** [comment]
Is this relevant to #152? Since the linters and formatters are already added I afraid it will conflict with this PR once the fixes are committed there

**Comment by tiagohconte** [comment]
@ynshung My idea here was to separate the code changes from the linter addition. This way, we can just rebase #152 with these changes. I used the same configuration for Eslint and Prettier used there to create this PR.

**Comment by ynshung** [comment]
I see, thanks for the clarification and the idea!

**Comment by tiagohconte** [comment]
I renamed the PR. It solves a lot of type errors :satisfied:

**Pull request merged**
