### PR TITLE
Stricter Typescript Linting

### PR DESCRIPTION
**Pull request by ynshung**
Currently, there are two rules specifically [no-explicit-any](https://typescript-eslint.io/rules/no-explicit-any/) and [no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars) that are set to warning. One of the reason is the large volume of types that are set to `any` in the codebase. As such, any help is great to trace down the explicit types for each of them.

You can see the error by running `npm run lint`.

See #152 for more info

### CODE REVIEW

**Comment by ynshung** [comment]
Hi @tiagohconte you could help look through some of the remaining errors in the linting

**Comment by tiagohconte** [comment]
@ynshung Is there a reason why `pingChanges` on `chromeEmitters.ts` is disable?

**Comment by tiagohconte** [comment]
It's done on PR #170. I need some help to test if everything still works fine :smiley:

**Comment by ynshung** [comment]
> @ynshung Is there a reason why `pingChanges` on `chromeEmitters.ts` is disable?

I think there's an error that made me comment out the function but I had forgotten what it is. I'm going to add it back since I'm not sure if I had accidentally break anything😅

**Pull request merged**
